# Generated by Django 4.2.5 on 2023-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_chatlog_question_remove_chatlog_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatlog",
            name="user",
        ),
        migrations.AddField(
            model_name="chatlog",
            name="last_updated_by",
            field=models.CharField(default="", max_length=100),
        ),
    ]
