# Generated by Django 4.2.5 on 2023-11-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_sqlLog_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sqlLog",
            old_name="context",
            new_name="model_name",
        ),
        migrations.AddField(
            model_name="sqlLog",
            name="prompt",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
