# Generated by Django 4.2.5 on 2023-11-18 07:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_context_sqlLog_model_name_sqlLog_prompt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sqlLog",
            name="question",
        ),
        migrations.RemoveField(
            model_name="sqlLog",
            name="temp",
        ),
    ]
