# Generated by Django 4.2.5 on 2023-11-21 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_sqlLog_comment_sqlLog_is_disliked_sqlLog_is_liked_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sqlLog",
            old_name="comment",
            new_name="dislike_comment",
        ),
    ]
