# Generated by Django 4.2.5 on 2023-11-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_rename_comment_sqlLog_dislike_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlLog",
            name="bookmark",
            field=models.BooleanField(default=False),
        ),
    ]
