# Generated by Django 4.2.5 on 2023-11-21 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_chatlog_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatlog",
            old_name="bookmark",
            new_name="is_bookmarked",
        ),
    ]
